language: objective-c
osx_image: xcode8.3
cache:
  directories:
    - Lib/vendor/bundle
install:
  - bundle install --path=vendor/bundle --binstubs=vendor/bin
script:
  - bundle exec rake "$ACTION" CONFIGURATION="$CONFIGURATION" DESTINATION="$DESTINATION" TESTCASE="$TESTCASE"
branches:
  only:
    - master
env:
  matrix:
    - ACTION=test:iphonesimulator CONFIGURATION=Debug DESTINATION='name=iPhone 4s,OS=9.3'
    - ACTION=test:iphonesimulator CONFIGURATION=Debug DESTINATION='name=iPhone 5,OS=9.3'
    - ACTION=test:iphonesimulator CONFIGURATION=Debug DESTINATION='name=iPhone 6s,OS=10.3' TESTCASE='MergedCellTests/testTableView'
    - ACTION=test:iphonesimulator CONFIGURATION=Debug DESTINATION='name=iPhone 6s,OS=10.3' TESTCASE='MergedCellTests/testColumnHeaderView'
    - ACTION=test:iphonesimulator CONFIGURATION=Debug DESTINATION='name=iPhone 6s,OS=10.3' TESTCASE='MergedCellTests/testRowHeaderView'
    - ACTION=test:iphonesimulator CONFIGURATION=Debug DESTINATION='name=iPhone 6s,OS=10.3' TESTCASE='MergedCellTests/testColumnAndRowHeaderView'
    - ACTION=test:iphonesimulator CONFIGURATION=Debug DESTINATION='name=iPhone 6s,OS=10.3' TESTCASE='MergedCellTests/testHorizontalCircularScrolling'
    - ACTION=test:iphonesimulator CONFIGURATION=Debug DESTINATION='name=iPhone 6s,OS=10.3' TESTCASE='MergedCellTests/testVerticalCircularScrolling'
    - ACTION=test:iphonesimulator CONFIGURATION=Debug DESTINATION='name=iPhone 6s,OS=10.3' TESTCASE='ScrollTests/testTableViewScrolling'
    - ACTION=test:iphonesimulator CONFIGURATION=Debug DESTINATION='name=iPhone 6s,OS=10.3' TESTCASE='ScrollTests/testColumnHeaderViewScrolling'
    - ACTION=test:iphonesimulator CONFIGURATION=Debug DESTINATION='name=iPhone 6s,OS=10.3' TESTCASE='ScrollTests/testRowHeaderViewScrolling'
    - ACTION=test:iphonesimulator CONFIGURATION=Debug DESTINATION='name=iPhone 6s,OS=10.3' TESTCASE='ScrollTests/testColumnAndRowHeaderViewScrolling'
    - ACTION=test:iphonesimulator CONFIGURATION=Debug DESTINATION='name=iPhone 6s,OS=10.3' TESTCASE='ScrollTests/testCircularScrolling'
    - ACTION=test:iphonesimulator CONFIGURATION=Debug DESTINATION='name=iPhone 6s,OS=10.3' TESTCASE='SelectionTests'
    - ACTION=test:iphonesimulator CONFIGURATION=Debug DESTINATION='name=iPhone 7 Plus,OS=10.3' TESTCASE='MergedCellTests/testTableView'
    - ACTION=test:iphonesimulator CONFIGURATION=Debug DESTINATION='name=iPhone 7 Plus,OS=10.3' TESTCASE='MergedCellTests/testColumnHeaderView'
    - ACTION=test:iphonesimulator CONFIGURATION=Debug DESTINATION='name=iPhone 7 Plus,OS=10.3' TESTCASE='MergedCellTests/testRowHeaderView'
    - ACTION=test:iphonesimulator CONFIGURATION=Debug DESTINATION='name=iPhone 7 Plus,OS=10.3' TESTCASE='MergedCellTests/testColumnAndRowHeaderView'
    - ACTION=test:iphonesimulator CONFIGURATION=Debug DESTINATION='name=iPhone 7 Plus,OS=10.3' TESTCASE='MergedCellTests/testHorizontalCircularScrolling'
    - ACTION=test:iphonesimulator CONFIGURATION=Debug DESTINATION='name=iPhone 7 Plus,OS=10.3' TESTCASE='MergedCellTests/testVerticalCircularScrolling'
    - ACTION=test:iphonesimulator CONFIGURATION=Debug DESTINATION='name=iPhone 7 Plus,OS=10.3' TESTCASE='ScrollTests/testTableViewScrolling'
    - ACTION=test:iphonesimulator CONFIGURATION=Debug DESTINATION='name=iPhone 7 Plus,OS=10.3' TESTCASE='ScrollTests/testColumnHeaderViewScrolling'
    - ACTION=test:iphonesimulator CONFIGURATION=Debug DESTINATION='name=iPhone 7 Plus,OS=10.3' TESTCASE='ScrollTests/testRowHeaderViewScrolling'
    - ACTION=test:iphonesimulator CONFIGURATION=Debug DESTINATION='name=iPhone 7 Plus,OS=10.3' TESTCASE='ScrollTests/testColumnAndRowHeaderViewScrolling'
    - ACTION=test:iphonesimulator CONFIGURATION=Debug DESTINATION='name=iPhone 7 Plus,OS=10.3' TESTCASE='ScrollTests/testCircularScrolling'
    - ACTION=test:iphonesimulator CONFIGURATION=Debug DESTINATION='name=iPhone 7 Plus,OS=10.3' TESTCASE='SelectionTests'
    - ACTION=test:iphonesimulator CONFIGURATION=Debug DESTINATION='name=iPad 2,OS=10.3' TESTCASE='MergedCellTests/testTableView'
    - ACTION=test:iphonesimulator CONFIGURATION=Debug DESTINATION='name=iPad 2,OS=10.3' TESTCASE='MergedCellTests/testColumnHeaderView'
    - ACTION=test:iphonesimulator CONFIGURATION=Debug DESTINATION='name=iPad 2,OS=10.3' TESTCASE='MergedCellTests/testRowHeaderView'
    - ACTION=test:iphonesimulator CONFIGURATION=Debug DESTINATION='name=iPad 2,OS=10.3' TESTCASE='MergedCellTests/testColumnAndRowHeaderView'
    - ACTION=test:iphonesimulator CONFIGURATION=Debug DESTINATION='name=iPad 2,OS=10.3' TESTCASE='MergedCellTests/testHorizontalCircularScrolling'
    - ACTION=test:iphonesimulator CONFIGURATION=Debug DESTINATION='name=iPad 2,OS=10.3' TESTCASE='MergedCellTests/testVerticalCircularScrolling'
    - ACTION=test:iphonesimulator CONFIGURATION=Debug DESTINATION='name=iPad 2,OS=10.3' TESTCASE='ScrollTests/testTableViewScrolling'
    - ACTION=test:iphonesimulator CONFIGURATION=Debug DESTINATION='name=iPad 2,OS=10.3' TESTCASE='ScrollTests/testColumnHeaderViewScrolling'
    - ACTION=test:iphonesimulator CONFIGURATION=Debug DESTINATION='name=iPad 2,OS=10.3' TESTCASE='ScrollTests/testRowHeaderViewScrolling'
    - ACTION=test:iphonesimulator CONFIGURATION=Debug DESTINATION='name=iPad 2,OS=10.3' TESTCASE='ScrollTests/testColumnAndRowHeaderViewScrolling'
    - ACTION=test:iphonesimulator CONFIGURATION=Debug DESTINATION='name=iPad 2,OS=10.3' TESTCASE='ScrollTests/testCircularScrolling'
    - ACTION=test:iphonesimulator CONFIGURATION=Debug DESTINATION='name=iPad 2,OS=10.3' TESTCASE='SelectionTests'
    - ACTION=test:iphonesimulator CONFIGURATION=Debug DESTINATION='name=iPad Air 2,OS=10.3' TESTCASE='MergedCellTests/testTableView'
    - ACTION=test:iphonesimulator CONFIGURATION=Debug DESTINATION='name=iPad Air 2,OS=10.3' TESTCASE='MergedCellTests/testColumnHeaderView'
    - ACTION=test:iphonesimulator CONFIGURATION=Debug DESTINATION='name=iPad Air 2,OS=10.3' TESTCASE='MergedCellTests/testRowHeaderView'
    - ACTION=test:iphonesimulator CONFIGURATION=Debug DESTINATION='name=iPad Air 2,OS=10.3' TESTCASE='MergedCellTests/testColumnAndRowHeaderView'
    - ACTION=test:iphonesimulator CONFIGURATION=Debug DESTINATION='name=iPad Air 2,OS=10.3' TESTCASE='MergedCellTests/testHorizontalCircularScrolling'
    - ACTION=test:iphonesimulator CONFIGURATION=Debug DESTINATION='name=iPad Air 2,OS=10.3' TESTCASE='MergedCellTests/testVerticalCircularScrolling'
    - ACTION=test:iphonesimulator CONFIGURATION=Debug DESTINATION='name=iPad Air 2,OS=10.3' TESTCASE='ScrollTests/testTableViewScrolling'
    - ACTION=test:iphonesimulator CONFIGURATION=Debug DESTINATION='name=iPad Air 2,OS=10.3' TESTCASE='ScrollTests/testColumnHeaderViewScrolling'
    - ACTION=test:iphonesimulator CONFIGURATION=Debug DESTINATION='name=iPad Air 2,OS=10.3' TESTCASE='ScrollTests/testRowHeaderViewScrolling'
    - ACTION=test:iphonesimulator CONFIGURATION=Debug DESTINATION='name=iPad Air 2,OS=10.3' TESTCASE='ScrollTests/testColumnAndRowHeaderViewScrolling'
    - ACTION=test:iphonesimulator CONFIGURATION=Debug DESTINATION='name=iPad Air 2,OS=10.3' TESTCASE='ScrollTests/testCircularScrolling'
    - ACTION=test:iphonesimulator CONFIGURATION=Debug DESTINATION='name=iPad Air 2,OS=10.3' TESTCASE='SelectionTests'
    - ACTION=test:iphonesimulator CONFIGURATION=Debug DESTINATION='name=iPad Pro (9.7-inch),OS=10.3' TESTCASE='MergedCellTests/testTableView'
    - ACTION=test:iphonesimulator CONFIGURATION=Debug DESTINATION='name=iPad Pro (9.7-inch),OS=10.3' TESTCASE='MergedCellTests/testColumnHeaderView'
    - ACTION=test:iphonesimulator CONFIGURATION=Debug DESTINATION='name=iPad Pro (9.7-inch),OS=10.3' TESTCASE='MergedCellTests/testRowHeaderView'
    - ACTION=test:iphonesimulator CONFIGURATION=Debug DESTINATION='name=iPad Pro (9.7-inch),OS=10.3' TESTCASE='MergedCellTests/testColumnAndRowHeaderView'
    - ACTION=test:iphonesimulator CONFIGURATION=Debug DESTINATION='name=iPad Pro (9.7-inch),OS=10.3' TESTCASE='MergedCellTests/testHorizontalCircularScrolling'
    - ACTION=test:iphonesimulator CONFIGURATION=Debug DESTINATION='name=iPad Pro (9.7-inch),OS=10.3' TESTCASE='MergedCellTests/testVerticalCircularScrolling'
    - ACTION=test:iphonesimulator CONFIGURATION=Debug DESTINATION='name=iPad Pro (9.7-inch),OS=10.3' TESTCASE='ScrollTests/testTableViewScrolling'
    - ACTION=test:iphonesimulator CONFIGURATION=Debug DESTINATION='name=iPad Pro (9.7-inch),OS=10.3' TESTCASE='ScrollTests/testColumnHeaderViewScrolling'
    - ACTION=test:iphonesimulator CONFIGURATION=Debug DESTINATION='name=iPad Pro (9.7-inch),OS=10.3' TESTCASE='ScrollTests/testRowHeaderViewScrolling'
    - ACTION=test:iphonesimulator CONFIGURATION=Debug DESTINATION='name=iPad Pro (9.7-inch),OS=10.3' TESTCASE='ScrollTests/testColumnAndRowHeaderViewScrolling'
    - ACTION=test:iphonesimulator CONFIGURATION=Debug DESTINATION='name=iPad Pro (9.7-inch),OS=10.3' TESTCASE='ScrollTests/testCircularScrolling'
    - ACTION=test:iphonesimulator CONFIGURATION=Debug DESTINATION='name=iPad Pro (9.7-inch),OS=10.3' TESTCASE='SelectionTests'
    - ACTION=test:iphonesimulator CONFIGURATION=Debug DESTINATION='name=iPad Pro (12.9-inch),OS=10.3' TESTCASE='MergedCellTests/testTableView'
    - ACTION=test:iphonesimulator CONFIGURATION=Debug DESTINATION='name=iPad Pro (12.9-inch),OS=10.3' TESTCASE='MergedCellTests/testColumnHeaderView'
    - ACTION=test:iphonesimulator CONFIGURATION=Debug DESTINATION='name=iPad Pro (12.9-inch),OS=10.3' TESTCASE='MergedCellTests/testRowHeaderView'
    - ACTION=test:iphonesimulator CONFIGURATION=Debug DESTINATION='name=iPad Pro (12.9-inch),OS=10.3' TESTCASE='MergedCellTests/testColumnAndRowHeaderView'
    - ACTION=test:iphonesimulator CONFIGURATION=Debug DESTINATION='name=iPad Pro (12.9-inch),OS=10.3' TESTCASE='MergedCellTests/testHorizontalCircularScrolling'
    - ACTION=test:iphonesimulator CONFIGURATION=Debug DESTINATION='name=iPad Pro (12.9-inch),OS=10.3' TESTCASE='MergedCellTests/testVerticalCircularScrolling'
    - ACTION=test:iphonesimulator CONFIGURATION=Debug DESTINATION='name=iPad Pro (12.9-inch),OS=10.3' TESTCASE='ScrollTests/testTableViewScrolling'
    - ACTION=test:iphonesimulator CONFIGURATION=Debug DESTINATION='name=iPad Pro (12.9-inch),OS=10.3' TESTCASE='ScrollTests/testColumnHeaderViewScrolling'
    - ACTION=test:iphonesimulator CONFIGURATION=Debug DESTINATION='name=iPad Pro (12.9-inch),OS=10.3' TESTCASE='ScrollTests/testRowHeaderViewScrolling'
    - ACTION=test:iphonesimulator CONFIGURATION=Debug DESTINATION='name=iPad Pro (12.9-inch),OS=10.3' TESTCASE='ScrollTests/testColumnAndRowHeaderViewScrolling'
    - ACTION=test:iphonesimulator CONFIGURATION=Debug DESTINATION='name=iPad Pro (12.9-inch),OS=10.3' TESTCASE='ScrollTests/testCircularScrolling'
    - ACTION=test:iphonesimulator CONFIGURATION=Debug DESTINATION='name=iPad Pro (12.9-inch),OS=10.3' TESTCASE='SelectionTests'
  global:
    - LANG=en_US.UTF-8
    - LC_ALL=en_US.UTF-8
